name: Pull Request Review

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set PR Author ID
        id: set_pr_author
        run: echo "PR_AUTHOR_GITHUB_ID=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV

      - name: Run PR Reviewer action
        uses: cAPRIcaT3/apprentice_stable@code-commit
        with:
          default: ${{ github.actor }}
          pr-author-github-id: ${{ github.event.pull_request.user.login }}
          ref: ${{ github.event.pull_request.head.ref }}
          PR_AUTHOR_GITHUB_ID: ${{ inputs.pr-author-github-id }}
          
