name: Pull Request Review

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PR Reviewer action
        uses: cAPRIcaT3/apprentice_stable@code-commit
        with:
          pr-author-github-id: ${{ github.event.pull_request.user.login }}
